bankapp:
  replicas: 1
  image:
    repository: oolumee/bankapp
    tag: "1"
  service:
    type: LoadBalancer
    port: 80
  env:
    datasourceUrl: jdbc:mysql://mysql-service:3306/bankappdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Test@123


mysql:
<<<<<<< HEAD
  image: mysql:8
=======
  image:
    repository: mysql
    tag: "2"

>>>>>>> 5f5803f5b1922409303b411fd5e0c5f227880cd3
  rootPassword: Test@123
  database: bankappdb

  service:
    type: ClusterIP
    port: 3306
