apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-bankapp
spec:
  replicas: {{ .Values.bankapp.replicas }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: bankapp
  template:
    metadata:
      labels:
        app: bankapp
    spec:
      containers:
        - name: bankapp
          image: "{{ .Values.bankapp.image.repository }}:{{ .Values.bankapp.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.bankapp.env.datasourceUrl | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.bankapp.env.username | quote }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.bankapp.env.password | quote }}

            # ðŸ”¥ REQUIRED for Ingress / reverse proxy
            - name: SERVER_FORWARD_HEADERS_STRATEGY
              value: framework

