{{- if .Values.bankapp.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bankapp-ingress
  annotations:
{{- range $key, $value := .Values.bankapp.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
spec:
  ingressClassName: {{ .Values.bankapp.ingress.className }}
  rules:
    - host: {{ .Values.bankapp.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bankapp-service
                port:
                  number: {{ .Values.bankapp.service.port }}
{{- end }}

